kind: pipeline
type: exec
name: portfolio

trigger:
    branch:
        - main

platform:
  os: linux
  arch: arm64

steps:
    - name: dependencies
      commands:
          - node -v
          - node i -g pnpm
          - pnpm i

    - name: build
      commands:
          - pnpm run build

    - name: move
      commands:
          - sudo cp -r build/* /var/www/portfolio