kind: pipeline
type: exec
name: portfolio

trigger:
    branch:
        - main

steps:
    - name: build
    #   image: node:20-alpine
      commands:
          - node -v
          - echo ${PWD}
          - echo ${DRONE_WORKSPACE}
