kind: pipeline
type: docker
name: portfolio

trigger:
    branch:
        - main

platform:
  os: linux
  arch: arm64

steps:
    - name: dependencies
      image: node:18.20-alpine
      volumes:
          - name: cache
            path: /tmp/cache
      commands:
          - node -v
          - npm i -g pnpm
          - pnpm i
          - pnpm run build
          - cp -r build/* /tmp/cache


volumes:
    - name: cache
      host:
        path: /var/www/portfolio
